#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt'
cookbook 'omnibus_updater'
cookbook 'git'
cookbook 'curl'
cookbook 'application', '3.0.0'

cookbook 'application_ruby'
