name             'liveedit-example'
maintainer       'Oliver Buchtala'
maintainer_email 'oliver.buchtala@gmail.com'
license          'All rights reserved'
description      'Installs/Configures liveedit-example'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
depends          'nodejs'
depends          'application_nodejs'
depends          'local_application'
