# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

CLIENT = 'example2.substance.io'
CLIENT_IP = '192.168.50.20'
SERVER = 'chefserver.substance.io'
SERVER_IP = '192.168.50.100'
NODE_NAME = 'example2'
INSTALL_ARGS = CLIENT + ' ' + SERVER + ' ' + SERVER_IP

$provision =<<PROVISION
# TODO: this should be done smarter
if [ ! -f /root/.is_configured ]; then
  echo "Registering hostname $1."
  hostname "$1"
  echo "$1" | tee /etc/hostname
  echo -e "127.0.0.2 `hostname` `hostname -s`" | tee -a /etc/hosts

  # Add an alias for the server
  echo -e "$3 $2" | tee -a /etc/hosts
  touch /root/.is_configured
fi
PROVISION

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = 'precise64_chef'
  config.vm.network 'private_network', ip: CLIENT_IP
  # we need more memory as otherwise Passenger Apache2 does not get built

  config.vm.provision 'shell' do |s|
    s.inline = $provision
    s.args   = INSTALL_ARGS
  end

  config.vm.provision :chef_client do |chef|
    chef.chef_server_url = 'https://chefserver.substance.io'
    chef.validation_key_path = '../chef-repo/.chef/chef-validator.pem'
    chef.validation_client_name = 'chef-validator'
    chef.node_name = NODE_NAME
  end

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", 512]
  end

end
